

export const startingQuestions = [
    {link: '/verify', 
            text: 'Verify Report', 
            answer: ["I would be happy to help. On the top right corner of your screen is a blue button named 'Verify Report'. Enter your corresponding report number in the text box and then click the button 'Show Report'. Another way to get your report is to scan your QR on the physical certificate. To do so using a smart phone, open the camera app, place the QR within frame of the picture and an icon should pop up. Click this icon and it will automatically redirect your phone to your browser with the report."], 
            followUp: [{button: "Do you need a hard copy?", action: "physicalCopy"}, {button: "Are you receiving an error?", action: "reportNotWorking"}, {button: "Is there anything else I can help with?", action: "mainMenu"}]},
    {link: '/vv', 
            text: 'Access Virtual Vault', 
            answer: ["I would be happy to help. Please click the triple line icon on the top right of screen, under 'My GSI', click the option 'Virtual Vault'.", "If you need to login into your account, please enter the necessary credentials then click 'Log In'.","Otherwise if you need to activate an account, place your Report and VirtualVault number provided on your physical or digital certificate, then click 'Activate'."],
            followUp: [{button: "Do you need your online copy certifcate for reference?", action: "verifyReport"}, {button: "Is there anything else I can help with?", action: "mainMenu"}]},
    {link: 'NA', 
            text: 'How to Submit for Grading?', 
            answer: ['In order to sumbit to ...']},
    {link: '/loststolen',
            text: 'Report Lost/Stolen Item',
            answer: ['We are sorry to hear this. Please contact us at info@gemscience.net with your corresponding report number for us to investigate.'],
            followUp: [{button: "Is there anything else I can help with?", action: "mainMenu"}] 
    },
    {link: '/contact', 
            text: 'Contact Us', 
            answer: ["To talk to us directly, please reach out to info@gemscience.net or call us at (212) 207-4140."], 
            followUp: [{button: "Is there anything else I can help with?", action: "mainMenu"}]},
  ]

export const promptReponse = [
    {id: 'default', 
          answer: ['Sorry, I do not understand. Please contact us with your inquiry at info@gemscience.net.'], 
          followUp: [{button: "Is there anything else I can help with?", action: "mainMenu"}]},
    {id: 'mainMenu', fn: 'EndChat'},
    {id: 'physicalCopy', 
          link: '/hardcopy', 
          text: 'I need a hard copy', 
          answer: ['Please reach out to the reatiler in which the item was purchased for a hard copy.'], 
          followUp: [{button: "Are you a retailer?", action: "retailerPhysicalCopy"}, 
                     {button: "Is there anything else I can help with?", action: "mainMenu"}]},
    {id: 'verifyReport', 
          link: '/verify', 
          text: 'Verify Report', 
            answer: ["I would be happy to help. On the top right corner of your screen is a blue button named 'Verify Report'. Enter your corresponding report number in the text box and then click the button 'Show Report'.", 
                     "Another way to get your report is to scan your QR on the physical certificate. To do so using a smart phone, open the camera app, place the QR within frame of the picture and an icon should pop up. Click this icon and it will automatically redirect your phone to your browser with the report.",
                    ], 
          followUp: [{button: "Do you need a hard copy?", action: "physicalCopy"},
                     {button: "Are you receiving an error?", action: "reportNotWorking"}, 
                     {button: "Is there anything else I can help with?", action: "mainMenu"}]},
    {id: 'reportNotWorking', 
          text: 'I am receving an error looking up my report.', 
          answer: ['We are sorry to hear this. Please contact us at info@gemscience.net with your corresponding report number for us to investigate.'], 
          followUp: [{button: "Is there anything else I can help with?", action: "mainMenu"}]},
    {id: 'lostStolen', 
          link: '/loststolen', 
          text: 'Report Lost or Stolen Item.', 
          answer: ["We are sorry to hear this. To input a report for a lost/stolen item please click the triple line icon on the top right of screen, under 'My GSI', click the option 'Lost & Found'.", "We will need your corresponding GSI Report Number, Lost Date, Purchase Location, First and Last Name, Email, Item Value and Description, and if the item was insured."], 
          followUp: [{button: "Is there anything else I can help with?", action: "mainMenu"}] },
    {id: 'jobPosting', 
          link: '/career', 
          text: 'GSI Careers', 
          answer: ['Thank you for your interest in joining GSI. In order to view open positions please head over https://gemscience.net/career to view the current job listings.', 'If the need more information about the listing, the listing that your are looking for is not here, or need to ask questions regarding your resume submission, please contact us by email at: careers@gemscience.net. We look forward to hearing from you!'],
          followUp: [{button: "Is there anything else I can help with?", action: "mainMenu"}]},
    {id: 'customerSupport', 
          link: '/contact', 
          text: 'Talk to customer support', 
          answer: ['I would be happy help with that. Please contact us at info@gemscience.net and we get back to you as soon as we can.'], 
          followUp: [{button: "Is there anything else I can help with?", action: "mainMenu"}]},
    {id: 'retailerPhysicalCopy', 
          text: 'I am a retailer requesting a hard copy', 
          answer: ['I would be happy help with that. Please contact us at info@gemscience.net and we get back to you as soon as we can.'], 
          followUp: [{button: "Is there anything else I can help with?", action: "mainMenu"}]},
    {id: 'vv',
          text: 'Access Virtual Vault',
          answer: ["I would be happy to help. Please click the triple line icon on the top right of screen, under 'My GSI', click the option 'Virtual Vault'.", "If you need to login into your account, please enter the necessary credentials then click 'Log In'.","Otherwise if you need to activate an account, place your Report and VirtualVault number provided on your physical or digital certificate, then click 'Activate'."],
          followUp: [{button: "Do you need your online copy certifcate for reference?", action: "verifyReport"}, {button: "Is there anything else I can help with?", action: "mainMenu"}]
    },
    {id: 'howToSubmitItems', text: '', },
    {id: 'certificateOffer'},
    {id: 'contactUs'}
  ]
